### ISSUE TITLE
[BMT] Show the active stories 

### ISSUE THREAD

**Issue by rebekkategtmeier** [andriisemenov/equihub-brain-issue-tracking#72]
Me as a founder, 
would like to see the active stories in my BMT so that I can see on one view what I am working and can link the stories to the flow. From the view of the host I would like to see that a team is active working on the stories decided or if they are inactive because the stories are not changing. 

![image](https://user-images.githubusercontent.com/76179547/123211291-8c26db00-d4c3-11eb-9b66-71bb73ca6ad4.png)

Acceptance Criteria & Outcomes: 

- [x] stories are shown in the field in the BMT 
- [ ] user can click on the story and it will be shown completly in the side bar 
- [ ] user can see who is working on which story 
- [ ] closed stories / sprint will be saved for the history 
- [ ] the host / team can see how much progress they have done over time 
- [x] by activating a new sprint the old sprint will be closed and the user gets a message about it 
- [x] there will only be one active sprint

**Comment by andriisemenov** [comment]
The intention is to discuss this story in this sprint on how to implement it.

**Comment by andriisemenov** [comment]
Activate the sprint with the button

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/124006157-33cb6e00-d9da-11eb-8ae6-876a94fa4e71.png)

**Comment by rebekkategtmeier** [comment]
Activate the Sprint will be done with a simple button. We chose the flag as the interaction point for the activation. 
![image](https://user-images.githubusercontent.com/76179547/124557822-37c41980-de3a-11eb-8d0d-a4fa194b4200.png)
![image](https://user-images.githubusercontent.com/76179547/124557864-46aacc00-de3a-11eb-87ea-475e5ca9a3ea.png)
![image](https://user-images.githubusercontent.com/76179547/124558015-735ee380-de3a-11eb-9809-f0101ed7f721.png)

**Comment by rebekkategtmeier** [comment]
@andriisemenov and @kochjh the sprint activation is ready do be implemented ;D

**Comment by andriisemenov** [comment]
Backend to set the active sprint is ready.
Sample usage:

mutation{
  setActiveStep(id:"95bde8bc-b4ba-4fda-9302-afce3bc645b0")
  {
    id
  }
}

**Comment by rebekkategtmeier** [comment]
Moin @kochjh  and @andriisemenov,
on Friday we have the Feedbackcycle with our perspective clients. 
Can you let me know if this will be ready by than?

**Comment by rebekkategtmeier** [comment]
Hi thanks for launching it. 
Following things are not working / missing as described in the story: 
- headlines are different than in the graphic 
- Stories in twin cannot be clicked and you just see the headline, as written above, it was decided to show it in the sidebar, if the sidebar works if not expand the field in the twin 
- Stories are floating above other twin sections see picture below 
![image](https://user-images.githubusercontent.com/76179547/132719213-5ac3169d-865f-4776-8cb2-dd7533cfe9f5.png)

**Comment by rebekkategtmeier** [comment]
should be named: 
Do you really want to activate this sprint? 
![image](https://user-images.githubusercontent.com/76179547/132725358-0a015451-6a7a-4edd-ac12-fc7ee0de9adb.png)

By the way when I click on the active sprint again it asks me again if I want to activate it and not if I want to close it.

**Comment by andriisemenov** [comment]
Fixed stories non-scrollable, but for now no clicking on the story yet. If we want a sidebar, it needs to be developed, was not planned with this ticket. Expanding, we can think of this, but which data do we show? tasks?

**Comment by andriisemenov** [comment]
@rebekkategtmeier Please reopen the ticket if you think its needed. I created a new ticket to detail how the story will be shown in the BMT. #110

**Comment by rebekkategtmeier** [comment]
@andriisemenov it is definatly needed to reopen the ticket as the bugs are not solved yet. 
I can still click on the flag of an open story and I am asked if I want to active the sprint even though it is already active and the texts and labels are not correct and therefore misleading as a user does not know what a step is.

**Comment by rebekkategtmeier** [comment]
![image](https://user-images.githubusercontent.com/76179547/143454324-bacb08f4-1dd6-42d5-9062-ae18b9807d4d.png)
